name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'
        allow-prereleases: true
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    
    - name: Install dependencies
      run: uv sync --all-extras --dev --no-sources
    
    - name: Setup idaes
      run: |
          sudo apt-get update
          sudo apt-get install liblapack3 liblapack-dev libgfortran5 libgomp1  # shared libraries for ipopt
          uv run idaes get-extensions
    
    - name: Run tests
      run: uv run pytest


  publish:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: pypi # Pypi uses trusted environements and is set up to trust the pypi environment.
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install Python 3.14
        run: uv python install 3.14
      - name: Bump version
        run: uv run hatch version patch
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Bump version"
      - name: Build types
        run: uv build --package ahuora-builder-types --no-sources
      - name: Build package
        run: uv build --package ahuora-builder --no-sources
      - name: Publish
        run: uv publish